//Autogenerated triple quantized liym file with draw function
int buildingtranslittricount = 6;
f32 buildingtranslitvertpos[] ATTRIBUTE_ALIGN(32) = {-11.471391, 5.754582, 2.570415, -11.471391, 3.817454, 1.217373, -11.471391, 5.754582, 1.217373, -11.471391, 6.664258, 2.570415, -11.471391, 8.601385, 1.217373, -11.471391, 8.601385, 2.570415, -11.471391, 9.871628, 2.570415, -11.471391, 11.808756, 1.217373, -11.471391, 11.808756, 2.570415, -11.471391, 3.817453, 2.570415, -11.471391, 6.664258, 1.217373, -11.471391, 9.871628, 1.217373};
uint16_t buildingtranslitvertposidx[] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 9, 1, 3, 10, 4, 6, 11, 7};
f32 buildingtranslitvertnor[] ATTRIBUTE_ALIGN(32) = {1.000000, 0.000000, 0.000000};
uint16_t buildingtranslitvertnoridx[] = {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
f32 buildingtranslittexcord[] ATTRIBUTE_ALIGN(32) = {0.504624, 0.293501, 0.748015, 0.997196, 0.504624, 0.997196, 0.748015, 0.293501};
uint16_t buildingtranslittexcordidx[] = {0, 1, 2, 3, 2, 0, 3, 2, 0, 0, 3, 1, 3, 1, 2, 3, 1, 2};

void ag_draw_buildingtranslit(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &buildingtranslitvertpos[0], 12);
	GX_SetArray(GX_VA_NRM, &buildingtranslitvertnor[0], 12);
	GX_SetArray(GX_VA_TEX0, &buildingtranslittexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_VNIDX16 | LV_TCIDX16, buildingtranslittricount, vtxfmt,
		NULL, NULL, buildingtranslitvertposidx,
		NULL, NULL, buildingtranslitvertnoridx,
		NULL, NULL, buildingtranslittexcordidx,
		NULL,
		NULL);
}

void ag_config_buildingtranslit(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_VNIDX16 | LV_TCIDX16, vtxfmt);
}