//Autogenerated triple quantized liym file with draw function
int daisytricount = 4;
f32 daisyvertpos[] ATTRIBUTE_ALIGN(32) = {-0.025000, -0.025000, 0.000000, 0.025000, -0.025000, 0.000000, 0.000000, 0.000000, -0.008217, 0.025000, 0.025000, 0.000000, -0.025000, 0.025000, 0.000000};
uint16_t daisyvertposidx[] = {0, 1, 2, 1, 3, 2, 3, 4, 2, 4, 0, 2};
f32 daisytexcord[] ATTRIBUTE_ALIGN(32) = {0.002554, 0.377968, 0.122446, 0.377968, 0.062500, 0.437914, 0.122446, 0.497860, 0.002554, 0.497860};
uint16_t daisytexcordidx[] = {0, 1, 2, 1, 3, 2, 3, 4, 2, 4, 0, 2};

void ag_draw_daisy(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &daisyvertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &daisytexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, daisytricount, vtxfmt,
		NULL, NULL, daisyvertposidx,
		NULL, NULL, NULL,
		NULL, NULL, daisytexcordidx,
		NULL,
		NULL);
}