//Autogenerated triple quantized liym file with draw function
int dandelion_seeding_seedstricount = 2;
f32 dandelion_seeding_seedsvertpos[] ATTRIBUTE_ALIGN(32) = {0.070000, -0.031568, -0.070000, -0.070000, -0.031568, 0.070000, -0.070000, -0.031568, -0.070000, 0.070000, -0.031568, 0.070000};
uint16_t dandelion_seeding_seedsvertposidx[] = {0, 1, 2, 0, 3, 1};
f32 dandelion_seeding_seedstexcord[] ATTRIBUTE_ALIGN(32) = {0.507689, 0.873392, 0.019579, 0.995419, 0.019579, 0.873392, 0.507689, 0.995419};
uint16_t dandelion_seeding_seedstexcordidx[] = {0, 1, 2, 0, 3, 1};

void ag_draw_dandelion_seeding_seeds(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &dandelion_seeding_seedsvertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &dandelion_seeding_seedstexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, dandelion_seeding_seedstricount, vtxfmt,
		NULL, NULL, dandelion_seeding_seedsvertposidx,
		NULL, NULL, NULL,
		NULL, NULL, dandelion_seeding_seedstexcordidx,
		NULL,
		NULL);
}

void ag_config_dandelion_seeding_seeds(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}