//Autogenerated triple quantized liym file with draw function
int dandelion_unfertilized_flowertricount = 17;
f32 dandelion_unfertilized_flowervertpos[] ATTRIBUTE_ALIGN(32) = {-0.048983, 0.015225, -0.016573, -0.030273, -0.042356, -0.016573, -0.000001, -0.000690, -0.006276, 0.030271, -0.042356, -0.016573, 0.048980, 0.015225, -0.016573, -0.000001, 0.050812, -0.016573, -0.000001, -0.000690, -0.006490, 0.047977, -0.000690, 0.036368, -0.000001, -0.000690, 0.036368, -0.047979, -0.000690, 0.036368, -0.047979, -0.000690, -0.016371, 0.014825, 0.044940, 0.036368, -0.014827, -0.046320, 0.036368, -0.014827, -0.046320, -0.016371, -0.038816, 0.027511, 0.036368, 0.038814, -0.028891, 0.036368, 0.038814, -0.028891, -0.016371, -0.038816, 0.027511, -0.016371, 0.047977, -0.000690, -0.016371, 0.014825, 0.044940, -0.016371};
uint16_t dandelion_unfertilized_flowervertposidx[] = {0, 1, 2, 1, 3, 2, 3, 4, 2, 4, 5, 2, 5, 0, 2, 6, 7, 8, 6, 9, 10, 6, 11, 8, 6, 12, 13, 6, 14, 8, 6, 15, 16, 6, 17, 14, 6, 8, 15, 6, 18, 7, 6, 8, 9, 6, 19, 11, 6, 8, 12};
f32 dandelion_unfertilized_flowertexcord[] ATTRIBUTE_ALIGN(32) = {0.170887, 0.758418, 0.004867, 0.707115, 0.125000, 0.624106, 0.004867, 0.541096, 0.170887, 0.489793, 0.273493, 0.624106, 0.124244, 0.624662, 0.003111, 0.501625, 0.124244, 0.501625, 0.245378, 0.501625, 0.245378, 0.653029, 0.124687, 0.625624, 0.245821, 0.748660, 0.124687, 0.748660, 0.003554, 0.748660, 0.003554, 0.597256, 0.124947, 0.624921, 0.247983, 0.503788, 0.247983, 0.624921, 0.247983, 0.746055, 0.096579, 0.746055, 0.096579, 0.503788, 0.003111, 0.653029, 0.245821, 0.597256};
uint16_t dandelion_unfertilized_flowertexcordidx[] = {0, 1, 2, 1, 3, 2, 3, 4, 2, 4, 5, 2, 5, 0, 2, 6, 7, 8, 6, 9, 10, 11, 12, 13, 11, 14, 15, 16, 17, 18, 16, 19, 20, 16, 21, 17, 16, 18, 19, 6, 22, 7, 6, 8, 9, 11, 23, 12, 11, 13, 14};

void ag_draw_dandelion_unfertilized_flower(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &dandelion_unfertilized_flowervertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &dandelion_unfertilized_flowertexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, dandelion_unfertilized_flowertricount, vtxfmt,
		NULL, NULL, dandelion_unfertilized_flowervertposidx,
		NULL, NULL, NULL,
		NULL, NULL, dandelion_unfertilized_flowertexcordidx,
		NULL,
		NULL);
}