//Autogenerated triple quantized liym file with draw function
int grassplaneclumptricount = 6;
f32 grassplaneclumpvertpos[] ATTRIBUTE_ALIGN(32) = {0.604372, 1.040179, -0.058377, -0.598982, -1.044091, 0.457062, 0.590774, 1.077477, 0.547185, -1.200659, -0.001956, -0.058377, 1.109110, 0.018798, 0.516291, -1.171677, -0.001655, 0.464555, 0.604372, -1.044091, -0.058377, -0.597934, 1.040267, 0.399664, -0.598982, 1.040179, -0.058377, -0.598982, -1.044091, -0.058377, 1.206049, -0.001956, -0.058377, 0.604372, -1.044091, 0.457062};
uint16_t grassplaneclumpvertposidx[] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 9, 1, 3, 10, 4, 6, 11, 7};
f32 grassplaneclumptexcord[] ATTRIBUTE_ALIGN(32) = {0.985224, 0.000000, 0.541159, 1.000000, 0.541159, 0.000000, 0.985224, 1.000000};
uint16_t grassplaneclumptexcordidx[] = {0, 1, 2, 0, 1, 2, 3, 2, 0, 0, 3, 1, 0, 3, 1, 3, 1, 2};
uint8_t grassplaneclumpmtxidx[] = {0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1};

void ag_draw_grassplaneclump(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &grassplaneclumpvertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &grassplaneclumptexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16 | LV_MX, grassplaneclumptricount, vtxfmt,
		NULL, NULL, grassplaneclumpvertposidx,
		NULL, NULL, NULL,
		NULL, NULL, grassplaneclumptexcordidx,
		grassplaneclumpmtxidx,
		NULL);
}

void ag_config_grassplaneclump(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16 | LV_MX, vtxfmt);
}