//Autogenerated triple quantized liym file with draw function
int idkflowertricount = 5;
f32 idkflowervertpos[] ATTRIBUTE_ALIGN(32) = {-0.017599, 0.005718, 0.000000, -0.010877, -0.014971, 0.000000, 0.000000, 0.000000, -0.005154, 0.010877, -0.014971, 0.000000, 0.017599, 0.005718, 0.000000, 0.000000, 0.018505, 0.000000};
uint16_t idkflowervertposidx[] = {0, 1, 2, 1, 3, 2, 3, 4, 2, 4, 5, 2, 5, 0, 2};
f32 idkflowertexcord[] ATTRIBUTE_ALIGN(32) = {0.123695, 0.455605, 0.147087, 0.381898, 0.184934, 0.435233, 0.222782, 0.381898, 0.246173, 0.455605, 0.184934, 0.501159};
uint16_t idkflowertexcordidx[] = {0, 1, 2, 1, 3, 2, 3, 4, 2, 4, 5, 2, 5, 0, 2};

void ag_draw_idkflower(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &idkflowervertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &idkflowertexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, idkflowertricount, vtxfmt,
		NULL, NULL, idkflowervertposidx,
		NULL, NULL, NULL,
		NULL, NULL, idkflowertexcordidx,
		NULL,
		NULL);
}