//Autogenerated triple quantized liym file with draw function
int doodle1tricount = 2;
f32 doodle1vertpos[] ATTRIBUTE_ALIGN(32) = {-1.000000, 1.000000, 0.000000, 1.000000, -1.000000, 0.000000, 1.000000, 1.000000, 0.000000, -1.000000, -1.000000, 0.000000};
uint16_t doodle1vertposidx[] = {0, 1, 2, 0, 3, 1};
f32 doodle1texcord[] ATTRIBUTE_ALIGN(32) = {1.000000, 0.000000, 0.000000, 1.000000, 0.000000, 0.000000, 1.000000, 1.000000};
uint16_t doodle1texcordidx[] = {0, 1, 2, 0, 3, 1};

void ag_draw_doodle1(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &doodle1vertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &doodle1texcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, doodle1tricount, vtxfmt,
		NULL, NULL, doodle1vertposidx,
		NULL, NULL, NULL,
		NULL, NULL, doodle1texcordidx,
		NULL,
		NULL);
}

void ag_config_doodle1(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int doodle1_config = LV_VPIDX16 | LV_TCIDX16;
