//Autogenerated triple quantized liym file with draw function
int gilldoodleAwaveArmAtricount = 5;
f32 gilldoodleAwaveArmAvertpos[] ATTRIBUTE_ALIGN(32) = {0.005889, 0.006862, 0.000000, 0.033133, 0.057764, 0.000000, -0.006657, 0.016541, 0.000000, -0.038919, -0.070208, 0.000000, -0.027448, -0.072717, 0.000000, 0.049980, 0.020484, 0.000000, -0.015977, 0.041275, 0.000000};
uint16_t gilldoodleAwaveArmAvertposidx[] = {0, 1, 2, 2, 3, 0, 3, 4, 0, 0, 5, 1, 1, 6, 2};
f32 gilldoodleAwaveArmAtexcord[] ATTRIBUTE_ALIGN(32) = {0.352773, 0.781982, 0.389076, 0.693850, 0.336054, 0.765224, 0.293064, 0.915421, 0.308349, 0.919766, 0.411527, 0.758397, 0.323635, 0.722399};
uint16_t gilldoodleAwaveArmAtexcordidx[] = {0, 1, 2, 2, 3, 0, 3, 4, 0, 0, 5, 1, 1, 6, 2};

void ag_draw_gilldoodleAwaveArmA(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleAwaveArmAvertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleAwaveArmAtexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleAwaveArmAtricount, vtxfmt,
		NULL, NULL, gilldoodleAwaveArmAvertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleAwaveArmAtexcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleAwaveArmA(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleAwaveArmA_config = LV_VPIDX16 | LV_TCIDX16;
