//Autogenerated triple quantized liym file with draw function
int gilldoodleAblowerBtricount = 11;
f32 gilldoodleAblowerBvertpos[] ATTRIBUTE_ALIGN(32) = {0.081140, 0.015345, 0.000000, -0.078314, -0.086569, 0.000000, 0.049237, -0.081441, 0.000000, 0.076422, 0.084001, 0.000000, 0.064355, 0.101626, 0.000000, -0.031509, 0.118105, 0.000000, 0.114836, 0.027891, 0.000000, -0.078314, 0.100192, 0.000000, -0.137461, 0.027782, 0.000000, -0.146978, -0.001970, 0.000000, -0.034306, -0.134523, 0.000000, 0.035810, -0.130222, 0.000000, 0.085083, -0.040217, 0.000000};
uint16_t gilldoodleAblowerBvertposidx[] = {0, 1, 2, 3, 4, 5, 0, 6, 3, 3, 5, 0, 5, 7, 0, 7, 8, 1, 8, 9, 1, 1, 10, 2, 7, 1, 0, 10, 11, 2, 2, 12, 0};
f32 gilldoodleAblowerBtexcord[] ATTRIBUTE_ALIGN(32) = {0.696021, 0.758908, 0.908502, 0.582455, 0.738534, 0.591333, 0.702308, 0.877780, 0.718387, 0.908296, 0.846132, 0.936828, 0.651119, 0.780631, 0.908502, 0.905814, 0.987318, 0.780442, 1.000000, 0.728929, 0.849858, 0.499426, 0.756425, 0.506874, 0.690766, 0.662708};
uint16_t gilldoodleAblowerBtexcordidx[] = {0, 1, 2, 3, 4, 5, 0, 6, 3, 3, 5, 0, 5, 7, 0, 7, 8, 1, 8, 9, 1, 1, 10, 2, 7, 1, 0, 10, 11, 2, 2, 12, 0};

void ag_draw_gilldoodleAblowerB(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleAblowerBvertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleAblowerBtexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleAblowerBtricount, vtxfmt,
		NULL, NULL, gilldoodleAblowerBvertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleAblowerBtexcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleAblowerB(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleAblowerB_config = LV_VPIDX16 | LV_TCIDX16;
