//Autogenerated triple quantized liym file with draw function
int gilldoodleBgetup3tricount = 10;
f32 gilldoodleBgetup3vertpos[] ATTRIBUTE_ALIGN(32) = {-0.134260, 0.111088, 0.000000, -0.179312, -0.032634, 0.000000, 0.188860, -0.096550, 0.000000, 0.166149, 0.387172, 0.000000, 0.073129, 0.403343, 0.000000, 0.226268, 0.179408, 0.000000, -0.107042, 0.335568, 0.000000, -0.138953, 0.202796, 0.000000, 0.205746, 0.090019, 0.000000, -0.163356, 0.080975, 0.000000, -0.163356, -0.237952, 0.000000, 0.108829, -0.277647, 0.000000};
uint16_t gilldoodleBgetup3vertposidx[] = {0, 1, 2, 3, 4, 5, 4, 6, 7, 5, 4, 7, 7, 0, 8, 5, 7, 8, 0, 9, 1, 1, 10, 11, 11, 2, 1, 2, 8, 0};
f32 gilldoodleBgetup3texcord[] ATTRIBUTE_ALIGN(32) = {0.313034, 0.700081, 0.362309, 0.732931, 0.384222, 0.464466, 0.218379, 0.481026, 0.212835, 0.548855, 0.289611, 0.437189, 0.236071, 0.680233, 0.281592, 0.703503, 0.320257, 0.452153, 0.323358, 0.721297, 0.432702, 0.721297, 0.446311, 0.522823};
uint16_t gilldoodleBgetup3texcordidx[] = {0, 1, 2, 3, 4, 5, 4, 6, 7, 5, 4, 7, 7, 0, 8, 5, 7, 8, 0, 9, 1, 1, 10, 11, 11, 2, 1, 2, 8, 0};

void ag_draw_gilldoodleBgetup3(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleBgetup3vertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleBgetup3texcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleBgetup3tricount, vtxfmt,
		NULL, NULL, gilldoodleBgetup3vertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleBgetup3texcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleBgetup3(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleBgetup3_config = LV_VPIDX16 | LV_TCIDX16;
