//Autogenerated triple quantized liym file with draw function
int gilldoodleAsurprisetricount = 12;
f32 gilldoodleAsurprisevertpos[] ATTRIBUTE_ALIGN(32) = {0.003126, -0.099765, 0.000000, 0.047935, -0.082140, 0.000000, 0.047470, -0.040612, 0.000000, -0.106206, -0.016421, 0.000000, -0.090570, -0.053218, 0.000000, 0.094934, 0.031478, 0.000000, -0.051498, -0.054293, 0.000000, -0.022564, -0.089309, 0.000000, 0.078703, 0.130849, 0.000000, -0.008524, 0.165147, 0.000000, 0.098120, 0.080663, 0.000000, -0.102323, 0.120393, 0.000000, -0.079254, -0.058130, 0.000000, 0.090652, -0.034643, 0.000000};
uint16_t gilldoodleAsurprisevertposidx[] = {0, 1, 2, 3, 4, 5, 6, 2, 5, 2, 6, 7, 7, 0, 2, 8, 9, 10, 9, 11, 5, 10, 9, 5, 11, 3, 5, 5, 4, 6, 4, 12, 6, 2, 13, 5};
f32 gilldoodleAsurprisetexcord[] ATTRIBUTE_ALIGN(32) = {0.487538, 0.458668, 0.547248, 0.428152, 0.546628, 0.356252, 0.341847, 0.314367, 0.362683, 0.378077, 0.609877, 0.231434, 0.414748, 0.379938, 0.453305, 0.440566, 0.588248, 0.059384, 0.472014, 0.000000, 0.614122, 0.146274, 0.347022, 0.077486, 0.377762, 0.386581, 0.604170, 0.345917};
uint16_t gilldoodleAsurprisetexcordidx[] = {0, 1, 2, 3, 4, 5, 6, 2, 5, 2, 6, 7, 7, 0, 2, 8, 9, 10, 9, 11, 5, 10, 9, 5, 11, 3, 5, 5, 4, 6, 4, 12, 6, 2, 13, 5};

void ag_draw_gilldoodleAsurprise(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleAsurprisevertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleAsurprisetexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleAsurprisetricount, vtxfmt,
		NULL, NULL, gilldoodleAsurprisevertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleAsurprisetexcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleAsurprise(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleAsurprise_config = LV_VPIDX16 | LV_TCIDX16;
