//Autogenerated triple quantized liym file with draw function
int gilldoodleBgetup1tricount = 13;
f32 gilldoodleBgetup1vertpos[] ATTRIBUTE_ALIGN(32) = {-0.102107, 0.086830, 0.000000, -0.219062, 0.024865, 0.000000, -0.303277, -0.111329, 0.000000, -0.207436, -0.137154, 0.000000, 0.205331, 0.000910, 0.000000, 0.151393, 0.168484, 0.000000, -0.093997, 0.127856, 0.000000, 0.106623, 0.197418, 0.000000, -0.092876, 0.185704, 0.000000, -0.311743, -0.024238, 0.000000, 0.010578, -0.237486, 0.000000, 0.047339, -0.227221, 0.000000, 0.186560, -0.088061, 0.000000, 0.179521, 0.169727, 0.000000, -0.005847, 0.270103, 0.000000};
uint16_t gilldoodleBgetup1vertposidx[] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 1, 9, 2, 2, 5, 0, 5, 7, 0, 3, 10, 11, 11, 12, 3, 12, 4, 3, 4, 13, 5, 5, 2, 3, 0, 7, 6, 7, 14, 8};
f32 gilldoodleBgetup1texcord[] ATTRIBUTE_ALIGN(32) = {0.565719, 0.230088, 0.507242, 0.261071, 0.465135, 0.329168, 0.513055, 0.342080, 0.719439, 0.273048, 0.692469, 0.189261, 0.569775, 0.209575, 0.670084, 0.174794, 0.570335, 0.180651, 0.460902, 0.285622, 0.622062, 0.392246, 0.640442, 0.387113, 0.710053, 0.317533, 0.706533, 0.188640, 0.613849, 0.138451};
uint16_t gilldoodleBgetup1texcordidx[] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 1, 9, 2, 2, 5, 0, 5, 7, 0, 3, 10, 11, 11, 12, 3, 12, 4, 3, 4, 13, 5, 5, 2, 3, 0, 7, 6, 7, 14, 8};

void ag_draw_gilldoodleBgetup1(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleBgetup1vertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleBgetup1texcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleBgetup1tricount, vtxfmt,
		NULL, NULL, gilldoodleBgetup1vertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleBgetup1texcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleBgetup1(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleBgetup1_config = LV_VPIDX16 | LV_TCIDX16;
