//Autogenerated triple quantized liym file with draw function
int gilldoodleBgetup4tricount = 9;
f32 gilldoodleBgetup4vertpos[] ATTRIBUTE_ALIGN(32) = {0.044781, -0.302152, 0.000000, 0.158533, 0.172108, 0.000000, -0.189119, 0.141681, 0.000000, -0.092094, -0.320402, 0.000000, -0.162486, -0.255385, 0.000000, 0.165703, -0.285104, 0.000000, 0.099873, 0.265261, 0.000000, 0.007723, 0.238537, 0.000000, -0.064234, 0.249943, 0.000000, -0.091609, 0.215724, 0.000000, -0.148926, 0.226757, 0.000000};
uint16_t gilldoodleBgetup4vertposidx[] = {0, 1, 2, 3, 0, 4, 0, 5, 1, 4, 0, 2, 1, 6, 7, 7, 8, 9, 1, 7, 9, 2, 1, 9, 10, 2, 9};
f32 gilldoodleBgetup4texcord[] ATTRIBUTE_ALIGN(32) = {0.563261, 0.744740, 0.620137, 0.507610, 0.446311, 0.522823, 0.494824, 0.753865, 0.459627, 0.721357, 0.623722, 0.736216, 0.590807, 0.461033, 0.544732, 0.474396, 0.508753, 0.468693, 0.495066, 0.485802, 0.466407, 0.480286};
uint16_t gilldoodleBgetup4texcordidx[] = {0, 1, 2, 3, 0, 4, 0, 5, 1, 4, 0, 2, 1, 6, 7, 7, 8, 9, 1, 7, 9, 2, 1, 9, 10, 2, 9};

void ag_draw_gilldoodleBgetup4(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleBgetup4vertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleBgetup4texcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleBgetup4tricount, vtxfmt,
		NULL, NULL, gilldoodleBgetup4vertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleBgetup4texcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleBgetup4(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleBgetup4_config = LV_VPIDX16 | LV_TCIDX16;
