//Autogenerated triple quantized liym file with draw function
int gilldoodleBgetup6tricount = 11;
f32 gilldoodleBgetup6vertpos[] ATTRIBUTE_ALIGN(32) = {0.017757, 0.258917, 0.000000, -0.065345, 0.269215, 0.000000, -0.113808, 0.246209, 0.000000, -0.154418, 0.005215, 0.000000, -0.152744, -0.101585, 0.000000, 0.149744, -0.088823, 0.000000, -0.090873, -0.233781, 0.000000, -0.013202, -0.258337, 0.000000, 0.167668, -0.237741, 0.000000, 0.163866, 0.082275, 0.000000, 0.110637, 0.234362, 0.000000, -0.150569, 0.235943, 0.000000, -0.166165, 0.023869, 0.000000};
uint16_t gilldoodleBgetup6vertposidx[] = {0, 1, 2, 3, 4, 5, 4, 6, 7, 5, 4, 7, 7, 8, 5, 5, 9, 3, 9, 10, 0, 11, 12, 2, 12, 3, 0, 2, 12, 0, 9, 0, 3};
f32 gilldoodleBgetup6texcord[] ATTRIBUTE_ALIGN(32) = {0.706225, 0.380759, 0.664674, 0.375610, 0.640442, 0.387113, 0.620137, 0.507610, 0.620975, 0.561011, 0.772218, 0.554629, 0.651910, 0.627108, 0.690745, 0.639386, 0.781180, 0.629089, 0.779279, 0.469081, 0.752665, 0.393037, 0.622062, 0.392246, 0.614264, 0.498284};
uint16_t gilldoodleBgetup6texcordidx[] = {0, 1, 2, 3, 4, 5, 4, 6, 7, 5, 4, 7, 7, 8, 5, 5, 9, 3, 9, 10, 0, 11, 12, 2, 12, 3, 0, 2, 12, 0, 9, 0, 3};

void ag_draw_gilldoodleBgetup6(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleBgetup6vertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleBgetup6texcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleBgetup6tricount, vtxfmt,
		NULL, NULL, gilldoodleBgetup6vertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleBgetup6texcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleBgetup6(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleBgetup6_config = LV_VPIDX16 | LV_TCIDX16;
