//Autogenerated triple quantized liym file with draw function
int gilldoodleBscrambletorsotricount = 15;
f32 gilldoodleBscrambletorsovertpos[] ATTRIBUTE_ALIGN(32) = {0.303417, 0.089145, 0.000000, 0.223268, 0.213513, 0.000000, 0.160623, 0.143498, 0.000000, -0.007966, 0.149947, 0.000000, -0.024549, 0.206143, 0.000000, -0.052186, 0.192325, 0.000000, -0.079824, 0.109412, 0.000000, -0.144311, 0.156396, 0.000000, -0.264995, 0.067956, 0.000000, 0.086923, 0.105727, 0.000000, -0.055871, -0.143011, 0.000000, -0.274208, -0.173412, 0.000000, -0.226303, -0.260931, 0.000000, -0.076139, -0.295938, 0.000000, 0.095214, -0.258167, 0.000000, 0.060206, -0.139326, 0.000000, 0.276701, -0.163278, 0.000000};
uint16_t gilldoodleBscrambletorsovertposidx[] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 3, 5, 6, 9, 3, 6, 6, 8, 10, 8, 11, 10, 11, 12, 10, 10, 13, 14, 15, 16, 9, 16, 0, 9, 10, 14, 15, 9, 6, 15, 6, 10, 15, 9, 0, 2};
f32 gilldoodleBscrambletorsotexcord[] ATTRIBUTE_ALIGN(32) = {0.401408, 0.334626, 0.444047, 0.294552, 0.420043, 0.263229, 0.422254, 0.178935, 0.441521, 0.170644, 0.436783, 0.156825, 0.408357, 0.143006, 0.424465, 0.110762, 0.394143, 0.050420, 0.407093, 0.226379, 0.321814, 0.154982, 0.311391, 0.045814, 0.281385, 0.069767, 0.269383, 0.144849, 0.282333, 0.230525, 0.323077, 0.213021, 0.314865, 0.321268};
uint16_t gilldoodleBscrambletorsotexcordidx[] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 3, 5, 6, 9, 3, 6, 6, 8, 10, 8, 11, 10, 11, 12, 10, 10, 13, 14, 15, 16, 9, 16, 0, 9, 10, 14, 15, 9, 6, 15, 6, 10, 15, 9, 0, 2};

void ag_draw_gilldoodleBscrambletorso(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleBscrambletorsovertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleBscrambletorsotexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleBscrambletorsotricount, vtxfmt,
		NULL, NULL, gilldoodleBscrambletorsovertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleBscrambletorsotexcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleBscrambletorso(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleBscrambletorso_config = LV_VPIDX16 | LV_TCIDX16;
