//Autogenerated triple quantized liym file with draw function
int gilldoodleAfalltorsoAtricount = 7;
f32 gilldoodleAfalltorsoAvertpos[] ATTRIBUTE_ALIGN(32) = {-0.000003, 0.052138, 0.000000, 0.109622, 0.006274, 0.000000, 0.007067, 0.059460, 0.000000, -0.079727, 0.072807, 0.000000, -0.091751, -0.014570, 0.000000, -0.074590, -0.068905, 0.000000, -0.019077, -0.100270, 0.000000, 0.074522, -0.085334, 0.000000, 0.073938, 0.078401, 0.000000};
uint16_t gilldoodleAfalltorsoAvertposidx[] = {0, 1, 2, 3, 4, 0, 4, 5, 0, 5, 6, 0, 6, 7, 0, 7, 1, 0, 1, 8, 2};
f32 gilldoodleAfalltorsoAtexcord[] ATTRIBUTE_ALIGN(32) = {0.166478, 0.333219, 0.312560, 0.412628, 0.175900, 0.320540, 0.060243, 0.297432, 0.044220, 0.448717, 0.067088, 0.542792, 0.141062, 0.597098, 0.265788, 0.571238, 0.265009, 0.287747};
uint16_t gilldoodleAfalltorsoAtexcordidx[] = {0, 1, 2, 3, 4, 0, 4, 5, 0, 5, 6, 0, 6, 7, 0, 7, 1, 0, 1, 8, 2};

void ag_draw_gilldoodleAfalltorsoA(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleAfalltorsoAvertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleAfalltorsoAtexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleAfalltorsoAtricount, vtxfmt,
		NULL, NULL, gilldoodleAfalltorsoAvertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleAfalltorsoAtexcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleAfalltorsoA(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleAfalltorsoA_config = LV_VPIDX16 | LV_TCIDX16;
