//Autogenerated triple quantized liym file with draw function
int gilldoodleBgetup9tricount = 13;
f32 gilldoodleBgetup9vertpos[] ATTRIBUTE_ALIGN(32) = {-0.034090, -0.339910, 0.000000, 0.161777, -0.246764, 0.000000, -0.012996, -0.013381, 0.000000, 0.188012, 0.260020, 0.000000, 0.120609, 0.332536, 0.000000, 0.050694, 0.312701, 0.000000, -0.189440, 0.197732, 0.000000, -0.198999, -0.119464, 0.000000, -0.120314, -0.308861, 0.000000, 0.172422, -0.307309, 0.000000, 0.164971, -0.086863, 0.000000, 0.163989, 0.064999, 0.000000, -0.115699, 0.382372, 0.000000, 0.199510, 0.168180, 0.000000};
uint16_t gilldoodleBgetup9vertposidx[] = {0, 1, 2, 3, 4, 5, 6, 7, 2, 7, 8, 2, 8, 0, 2, 0, 9, 1, 1, 10, 2, 10, 11, 2, 12, 6, 5, 6, 2, 5, 2, 11, 5, 11, 13, 5, 13, 3, 5};
f32 gilldoodleBgetup9texcord[] ATTRIBUTE_ALIGN(32) = {0.082455, 0.925837, 0.180388, 0.879264, 0.098428, 0.758365, 0.181109, 0.630161, 0.146612, 0.599615, 0.113654, 0.613540, 0.011133, 0.671238, 0.000000, 0.815614, 0.039342, 0.910312, 0.185711, 0.909536, 0.181985, 0.799314, 0.176663, 0.712377, 0.032031, 0.590631, 0.189969, 0.667357};
uint16_t gilldoodleBgetup9texcordidx[] = {0, 1, 2, 3, 4, 5, 6, 7, 2, 7, 8, 2, 8, 0, 2, 0, 9, 1, 1, 10, 2, 10, 11, 2, 12, 6, 5, 6, 2, 5, 2, 11, 5, 11, 13, 5, 13, 3, 5};

void ag_draw_gilldoodleBgetup9(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleBgetup9vertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleBgetup9texcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleBgetup9tricount, vtxfmt,
		NULL, NULL, gilldoodleBgetup9vertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleBgetup9texcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleBgetup9(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleBgetup9_config = LV_VPIDX16 | LV_TCIDX16;
