//Autogenerated triple quantized liym file with draw function
int gilldoodleBscramblearmBtricount = 7;
f32 gilldoodleBscramblearmBvertpos[] ATTRIBUTE_ALIGN(32) = {0.048994, -0.126583, 0.000000, 0.055095, -0.137969, 0.000000, 0.078940, -0.137624, 0.000000, -0.078486, 0.110002, 0.000000, -0.030888, 0.022483, 0.000000, -0.008625, 0.029392, 0.000000, 0.021316, 0.083132, 0.000000, -0.010160, 0.133918, 0.000000, -0.076183, 0.023250, 0.000000};
uint16_t gilldoodleBscramblearmBvertposidx[] = {0, 1, 2, 3, 4, 5, 6, 7, 3, 3, 8, 4, 4, 0, 5, 0, 2, 5, 5, 6, 3};
f32 gilldoodleBscramblearmBtexcord[] ATTRIBUTE_ALIGN(32) = {0.242234, 0.130250, 0.244326, 0.135943, 0.252501, 0.135771, 0.198527, 0.011958, 0.214846, 0.055717, 0.222479, 0.052263, 0.232744, 0.025393, 0.221953, 0.000000, 0.199317, 0.055334};
uint16_t gilldoodleBscramblearmBtexcordidx[] = {0, 1, 2, 3, 4, 5, 6, 7, 3, 3, 8, 4, 4, 0, 5, 0, 2, 5, 5, 6, 3};

void ag_draw_gilldoodleBscramblearmB(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleBscramblearmBvertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleBscramblearmBtexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleBscramblearmBtricount, vtxfmt,
		NULL, NULL, gilldoodleBscramblearmBvertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleBscramblearmBtexcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleBscramblearmB(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleBscramblearmB_config = LV_VPIDX16 | LV_TCIDX16;
