//Autogenerated triple quantized liym file with draw function
int gilldoodleAwavetricount = 12;
f32 gilldoodleAwavevertpos[] ATTRIBUTE_ALIGN(32) = {0.112923, 0.100487, 0.000000, 0.089987, 0.118936, 0.000000, 0.026753, 0.126924, 0.000000, 0.058155, -0.161528, 0.000000, 0.120098, -0.036781, 0.000000, -0.007659, -0.084099, 0.000000, -0.001637, 0.126924, 0.000000, -0.084243, 0.010466, 0.000000, -0.045083, 0.114635, 0.000000, -0.070893, 0.082803, 0.000000, -0.089390, -0.017424, 0.000000, -0.078206, -0.082808, 0.000000, -0.018844, -0.132707, 0.000000, -0.011961, -0.165829, 0.000000};
uint16_t gilldoodleAwavevertposidx[] = {0, 1, 2, 3, 4, 5, 2, 6, 7, 6, 8, 9, 9, 7, 6, 7, 0, 2, 0, 7, 4, 7, 10, 5, 4, 7, 5, 10, 11, 5, 5, 12, 3, 12, 13, 3};
f32 gilldoodleAwavetexcord[] ATTRIBUTE_ALIGN(32) = {0.922839, 0.045774, 0.892276, 0.013831, 0.808014, 0.000000, 0.849858, 0.499426, 0.932400, 0.283441, 0.762157, 0.365366, 0.770182, 0.000000, 0.660106, 0.201636, 0.712288, 0.021278, 0.677895, 0.076392, 0.653247, 0.249925, 0.668151, 0.363132, 0.747254, 0.449526, 0.756425, 0.506874};
uint16_t gilldoodleAwavetexcordidx[] = {0, 1, 2, 3, 4, 5, 2, 6, 7, 6, 8, 9, 9, 7, 6, 7, 0, 2, 0, 7, 4, 7, 10, 5, 4, 7, 5, 10, 11, 5, 5, 12, 3, 12, 13, 3};

void ag_draw_gilldoodleAwave(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleAwavevertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleAwavetexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleAwavetricount, vtxfmt,
		NULL, NULL, gilldoodleAwavevertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleAwavetexcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleAwave(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleAwave_config = LV_VPIDX16 | LV_TCIDX16;
