//Autogenerated triple quantized liym file with draw function
int gilldoodleBgetup5tricount = 12;
f32 gilldoodleBgetup5vertpos[] ATTRIBUTE_ALIGN(32) = {-0.198447, -0.244967, 0.000000, 0.055889, -0.240650, 0.000000, -0.135803, -0.059796, 0.000000, 0.119244, 0.281492, 0.000000, -0.191791, 0.281492, 0.000000, -0.185550, 0.059967, 0.000000, -0.232534, -0.004521, 0.000000, -0.149621, -0.032158, 0.000000, -0.191999, -0.076378, 0.000000, -0.236219, -0.171267, 0.000000, 0.242025, -0.005145, 0.000000, 0.219565, 0.187262, 0.000000, 0.238282, -0.137658, 0.000000, 0.226454, -0.178685, 0.000000};
uint16_t gilldoodleBgetup5vertposidx[] = {0, 1, 2, 3, 4, 5, 5, 6, 7, 2, 8, 9, 5, 7, 3, 7, 2, 10, 11, 7, 10, 11, 3, 7, 12, 10, 1, 1, 10, 2, 1, 13, 12, 9, 0, 2};
f32 gilldoodleBgetup5texcord[] ATTRIBUTE_ALIGN(32) = {0.420043, 0.263229, 0.507242, 0.261071, 0.441521, 0.170644, 0.528963, 0.000000, 0.422325, 0.000000, 0.424465, 0.110762, 0.408357, 0.143006, 0.436783, 0.156825, 0.422254, 0.178935, 0.407093, 0.226379, 0.571058, 0.143318, 0.563358, 0.047115, 0.569775, 0.209575, 0.565719, 0.230088};
uint16_t gilldoodleBgetup5texcordidx[] = {0, 1, 2, 3, 4, 5, 5, 6, 7, 2, 8, 9, 5, 7, 3, 7, 2, 10, 11, 7, 10, 11, 3, 7, 12, 10, 1, 1, 10, 2, 1, 13, 12, 9, 0, 2};

void ag_draw_gilldoodleBgetup5(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleBgetup5vertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleBgetup5texcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleBgetup5tricount, vtxfmt,
		NULL, NULL, gilldoodleBgetup5vertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleBgetup5texcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleBgetup5(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleBgetup5_config = LV_VPIDX16 | LV_TCIDX16;
