//Autogenerated triple quantized liym file with draw function
int gilldoodleBscramblelegsAtricount = 11;
f32 gilldoodleBscramblelegsAvertpos[] ATTRIBUTE_ALIGN(32) = {0.020968, 0.047851, 0.000000, -0.112282, -0.046877, 0.000000, -0.044840, -0.149852, 0.000000, -0.011933, 0.087836, 0.000000, -0.028998, 0.108907, 0.000000, -0.177007, -0.011891, 0.000000, -0.181081, -0.037635, 0.000000, -0.078335, -0.137310, 0.000000, 0.103169, -0.130709, 0.000000, 0.105432, -0.077901, 0.000000, 0.177375, -0.103273, 0.000000, 0.179876, -0.070307, 0.000000, 0.071938, 0.064680, 0.000000};
uint16_t gilldoodleBscramblelegsAvertposidx[] = {0, 1, 2, 3, 4, 1, 1, 5, 6, 6, 7, 1, 7, 2, 1, 2, 8, 9, 8, 10, 9, 10, 11, 9, 9, 12, 0, 0, 3, 1, 9, 0, 2};
f32 gilldoodleBscramblelegsAtexcord[] ATTRIBUTE_ALIGN(32) = {0.240933, 0.189406, 0.174308, 0.236769, 0.208029, 0.288257, 0.224483, 0.169413, 0.215950, 0.158878, 0.141945, 0.219277, 0.139908, 0.232149, 0.191282, 0.281986, 0.282034, 0.278686, 0.283165, 0.252282, 0.319136, 0.264967, 0.320387, 0.248484, 0.266418, 0.180991};
uint16_t gilldoodleBscramblelegsAtexcordidx[] = {0, 1, 2, 3, 4, 1, 1, 5, 6, 6, 7, 1, 7, 2, 1, 2, 8, 9, 8, 10, 9, 10, 11, 9, 9, 12, 0, 0, 3, 1, 9, 0, 2};

void ag_draw_gilldoodleBscramblelegsA(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleBscramblelegsAvertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleBscramblelegsAtexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleBscramblelegsAtricount, vtxfmt,
		NULL, NULL, gilldoodleBscramblelegsAvertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleBscramblelegsAtexcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleBscramblelegsA(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleBscramblelegsA_config = LV_VPIDX16 | LV_TCIDX16;
