//Autogenerated triple quantized liym file with draw function
int gilldoodleBgetup10tricount = 8;
f32 gilldoodleBgetup10vertpos[] ATTRIBUTE_ALIGN(32) = {-0.054530, 0.313156, 0.000000, -0.173186, 0.293656, 0.000000, -0.195232, 0.155997, 0.000000, -0.195810, -0.070143, 0.000000, -0.178917, -0.202997, 0.000000, -0.062447, -0.304509, 0.000000, -0.140661, -0.288540, 0.000000, 0.116663, -0.283977, 0.000000, 0.163894, 0.112708, 0.000000, 0.101803, 0.267965, 0.000000};
uint16_t gilldoodleBgetup10vertposidx[] = {0, 1, 2, 3, 4, 5, 4, 6, 5, 5, 7, 3, 7, 8, 3, 8, 9, 2, 3, 8, 2, 9, 0, 2};
f32 gilldoodleBgetup10texcord[] ATTRIBUTE_ALIGN(32) = {0.854976, 0.370940, 0.792013, 0.388620, 0.779279, 0.469081, 0.772218, 0.554629, 0.781180, 0.629089, 0.840115, 0.682908, 0.801008, 0.674924, 0.929670, 0.672642, 0.966039, 0.471887, 0.938274, 0.398886};
uint16_t gilldoodleBgetup10texcordidx[] = {0, 1, 2, 3, 4, 5, 4, 6, 5, 5, 7, 3, 7, 8, 3, 8, 9, 2, 3, 8, 2, 9, 0, 2};

void ag_draw_gilldoodleBgetup10(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleBgetup10vertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleBgetup10texcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleBgetup10tricount, vtxfmt,
		NULL, NULL, gilldoodleBgetup10vertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleBgetup10texcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleBgetup10(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleBgetup10_config = LV_VPIDX16 | LV_TCIDX16;
