//Autogenerated triple quantized liym file with draw function
int gilldoodleBgetup2tricount = 9;
f32 gilldoodleBgetup2vertpos[] ATTRIBUTE_ALIGN(32) = {-0.147880, 0.187307, 0.000000, -0.197643, -0.132968, 0.000000, 0.259095, 0.064227, 0.000000, -0.301505, -0.258298, 0.000000, -0.099366, -0.331069, 0.000000, -0.318575, -0.302320, 0.000000, 0.241127, -0.269978, 0.000000, 0.286946, -0.031902, 0.000000, 0.320187, 0.164847, 0.000000, 0.157576, 0.257383, 0.000000, 0.021918, 0.273554, 0.000000};
uint16_t gilldoodleBgetup2vertposidx[] = {0, 1, 2, 1, 3, 4, 3, 5, 4, 4, 6, 1, 6, 7, 1, 7, 2, 1, 2, 8, 9, 9, 10, 2, 10, 0, 2};
f32 gilldoodleBgetup2texcord[] ATTRIBUTE_ALIGN(32) = {0.188810, 0.396127, 0.079004, 0.371246, 0.146612, 0.599615, 0.036035, 0.319315, 0.011086, 0.420385, 0.020942, 0.310780, 0.032031, 0.590631, 0.113654, 0.613540, 0.181109, 0.630161, 0.212835, 0.548855, 0.218379, 0.481026};
uint16_t gilldoodleBgetup2texcordidx[] = {0, 1, 2, 1, 3, 4, 3, 5, 4, 4, 6, 1, 6, 7, 1, 7, 2, 1, 2, 8, 9, 9, 10, 2, 10, 0, 2};

void ag_draw_gilldoodleBgetup2(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleBgetup2vertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleBgetup2texcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleBgetup2tricount, vtxfmt,
		NULL, NULL, gilldoodleBgetup2vertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleBgetup2texcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleBgetup2(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleBgetup2_config = LV_VPIDX16 | LV_TCIDX16;
