//Autogenerated triple quantized liym file with draw function
int gilldoodleBgetup12tricount = 8;
f32 gilldoodleBgetup12vertpos[] ATTRIBUTE_ALIGN(32) = {0.187095, -0.039705, 0.000000, 0.185167, 0.046759, 0.000000, -0.154377, 0.061227, 0.000000, 0.165063, 0.270297, 0.000000, -0.042967, 0.270584, 0.000000, -0.138107, 0.187638, 0.000000, -0.140885, -0.201587, 0.000000, 0.145242, -0.153057, 0.000000, -0.055990, -0.399782, 0.000000, 0.159882, -0.361000, 0.000000};
uint16_t gilldoodleBgetup12vertposidx[] = {0, 1, 2, 1, 3, 4, 4, 5, 1, 5, 2, 1, 2, 6, 7, 6, 8, 7, 8, 9, 7, 7, 0, 2};
f32 gilldoodleBgetup12texcord[] ATTRIBUTE_ALIGN(32) = {0.459627, 0.721357, 0.432702, 0.721297, 0.410744, 0.980855, 0.362309, 0.732931, 0.343330, 0.896990, 0.364988, 0.971160, 0.505774, 0.966597, 0.494824, 0.753865, 0.576558, 0.902150, 0.563261, 0.744740};
uint16_t gilldoodleBgetup12texcordidx[] = {0, 1, 2, 1, 3, 4, 4, 5, 1, 5, 2, 1, 2, 6, 7, 6, 8, 7, 8, 9, 7, 7, 0, 2};

void ag_draw_gilldoodleBgetup12(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleBgetup12vertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleBgetup12texcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleBgetup12tricount, vtxfmt,
		NULL, NULL, gilldoodleBgetup12vertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleBgetup12texcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleBgetup12(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleBgetup12_config = LV_VPIDX16 | LV_TCIDX16;
