//Autogenerated triple quantized liym file with draw function
int gilldoodleAblowerAtricount = 11;
f32 gilldoodleAblowerAvertpos[] ATTRIBUTE_ALIGN(32) = {-0.046366, -0.118870, 0.000000, 0.039652, -0.122213, 0.000000, 0.060176, -0.095205, 0.000000, -0.083661, -0.078838, 0.000000, 0.083384, -0.064858, 0.000000, 0.025313, 0.083547, 0.000000, -0.027023, -0.132497, 0.000000, 0.086610, 0.046625, 0.000000, 0.062952, 0.101470, 0.000000, -0.001858, 0.100205, 0.000000, -0.103735, 0.062397, 0.000000, -0.021544, 0.111329, 0.000000, -0.073900, 0.106910, 0.000000};
uint16_t gilldoodleAblowerAvertposidx[] = {0, 1, 2, 3, 4, 5, 0, 6, 1, 0, 2, 3, 2, 4, 3, 4, 7, 5, 7, 8, 5, 5, 9, 10, 9, 11, 10, 12, 10, 11, 10, 3, 5};
f32 gilldoodleAblowerAtexcord[] ATTRIBUTE_ALIGN(32) = {0.081751, 0.976406, 0.196375, 0.982193, 0.223725, 0.935433, 0.032054, 0.907095, 0.254651, 0.882890, 0.177268, 0.625941, 0.107527, 1.000000, 0.258950, 0.689868, 0.227423, 0.594909, 0.141062, 0.597098, 0.005304, 0.662559, 0.114828, 0.577839, 0.045062, 0.585490};
uint16_t gilldoodleAblowerAtexcordidx[] = {0, 1, 2, 3, 4, 5, 0, 6, 1, 0, 2, 3, 2, 4, 3, 4, 7, 5, 7, 8, 5, 5, 9, 10, 9, 11, 10, 12, 10, 11, 10, 3, 5};

void ag_draw_gilldoodleAblowerA(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleAblowerAvertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleAblowerAtexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleAblowerAtricount, vtxfmt,
		NULL, NULL, gilldoodleAblowerAvertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleAblowerAtexcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleAblowerA(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleAblowerA_config = LV_VPIDX16 | LV_TCIDX16;
