//Autogenerated triple quantized liym file with draw function
int gilldoodleBdripBtricount = 4;
f32 gilldoodleBdripBvertpos[] ATTRIBUTE_ALIGN(32) = {-0.021325, -0.047022, 0.000000, 0.014501, -0.057258, 0.000000, 0.037533, -0.041264, 0.000000, 0.013222, 0.064296, 0.000000, -0.034760, 0.020152, 0.000000, -0.009170, 0.061097, 0.000000};
uint16_t gilldoodleBdripBvertposidx[] = {0, 1, 2, 2, 3, 4, 3, 5, 4, 4, 0, 2};
f32 gilldoodleBdripBtexcord[] ATTRIBUTE_ALIGN(32) = {0.012882, 0.098501, 0.025166, 0.103619, 0.033062, 0.095622, 0.024727, 0.042842, 0.008276, 0.064914, 0.017050, 0.044441};
uint16_t gilldoodleBdripBtexcordidx[] = {0, 1, 2, 2, 3, 4, 3, 5, 4, 4, 0, 2};

void ag_draw_gilldoodleBdripB(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleBdripBvertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleBdripBtexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleBdripBtricount, vtxfmt,
		NULL, NULL, gilldoodleBdripBvertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleBdripBtexcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleBdripB(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleBdripB_config = LV_VPIDX16 | LV_TCIDX16;
