//Autogenerated triple quantized liym file with draw function
int gilldoodleAfalltorsoBtricount = 11;
f32 gilldoodleAfalltorsoBvertpos[] ATTRIBUTE_ALIGN(32) = {0.026296, -0.080213, 0.000000, 0.060064, 0.054695, 0.000000, -0.057808, 0.038855, 0.000000, -0.080656, -0.020777, 0.000000, -0.090564, -0.041140, 0.000000, -0.077659, -0.069101, 0.000000, -0.059019, -0.084873, 0.000000, 0.077915, -0.064082, 0.000000, 0.109460, -0.034688, 0.000000, 0.085754, 0.044240, 0.000000, 0.031130, 0.089712, 0.000000, 0.003374, 0.085875, 0.000000, -0.028285, 0.081499, 0.000000};
uint16_t gilldoodleAfalltorsoBvertposidx[] = {0, 1, 2, 3, 4, 5, 5, 6, 3, 6, 0, 3, 0, 7, 1, 7, 8, 9, 1, 7, 9, 1, 10, 11, 11, 12, 2, 2, 3, 0, 2, 1, 11};
f32 gilldoodleAfalltorsoBtexcord[] ATTRIBUTE_ALIGN(32) = {0.408307, 0.674147, 0.453305, 0.440566, 0.296234, 0.467992, 0.265788, 0.571238, 0.252585, 0.606496, 0.269781, 0.654907, 0.294620, 0.682215, 0.477092, 0.646218, 0.519127, 0.595324, 0.487538, 0.458668, 0.414748, 0.379938, 0.377762, 0.386581, 0.335576, 0.394158};
uint16_t gilldoodleAfalltorsoBtexcordidx[] = {0, 1, 2, 3, 4, 5, 5, 6, 3, 6, 0, 3, 0, 7, 1, 7, 8, 9, 1, 7, 9, 1, 10, 11, 11, 12, 2, 2, 3, 0, 2, 1, 11};

void ag_draw_gilldoodleAfalltorsoB(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleAfalltorsoBvertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleAfalltorsoBtexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleAfalltorsoBtricount, vtxfmt,
		NULL, NULL, gilldoodleAfalltorsoBvertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleAfalltorsoBtexcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleAfalltorsoB(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleAfalltorsoB_config = LV_VPIDX16 | LV_TCIDX16;
