//Autogenerated triple quantized liym file with draw function
int gilldoodleAhearttricount = 5;
f32 gilldoodleAheartvertpos[] ATTRIBUTE_ALIGN(32) = {0.021182, 0.008550, 0.000000, -0.005894, 0.027882, 0.000000, -0.012125, 0.019075, 0.000000, -0.015851, -0.035596, 0.000000, 0.013274, -0.051030, 0.000000, 0.023978, 0.029625, 0.000000, -0.024564, 0.001495, 0.000000};
uint16_t gilldoodleAheartvertposidx[] = {0, 1, 2, 3, 4, 0, 0, 5, 1, 0, 2, 6, 6, 3, 0};
f32 gilldoodleAhearttexcord[] ATTRIBUTE_ALIGN(32) = {0.596314, 0.834263, 0.560234, 0.800792, 0.551930, 0.816041, 0.546966, 0.910699, 0.585777, 0.937421, 0.600041, 0.797775, 0.535355, 0.846479};
uint16_t gilldoodleAhearttexcordidx[] = {0, 1, 2, 3, 4, 0, 0, 5, 1, 0, 2, 6, 6, 3, 0};

void ag_draw_gilldoodleAheart(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleAheartvertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleAhearttexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleAhearttricount, vtxfmt,
		NULL, NULL, gilldoodleAheartvertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleAhearttexcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleAheart(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleAheart_config = LV_VPIDX16 | LV_TCIDX16;
