//Autogenerated triple quantized liym file with draw function
int gilldoodleAfalleyesBtricount = 6;
f32 gilldoodleAfalleyesBvertpos[] ATTRIBUTE_ALIGN(32) = {0.084441, 0.021104, 0.000000, 0.005595, -0.008837, 0.000000, 0.016490, -0.012835, 0.000000, -0.065855, -0.016871, 0.000000, 0.105796, -0.002285, 0.000000, -0.068389, 0.019450, 0.000000, -0.078080, 0.000274, 0.000000};
uint16_t gilldoodleAfalleyesBvertposidx[] = {0, 1, 2, 3, 2, 1, 2, 4, 0, 0, 5, 1, 1, 5, 3, 5, 6, 3};
f32 gilldoodleAfalleyesBtexcord[] ATTRIBUTE_ALIGN(32) = {0.246456, 0.018399, 0.141390, 0.070240, 0.155908, 0.077162, 0.046178, 0.084150, 0.274913, 0.058896, 0.042802, 0.021264, 0.029889, 0.054465};
uint16_t gilldoodleAfalleyesBtexcordidx[] = {0, 1, 2, 3, 2, 1, 2, 4, 0, 0, 5, 1, 1, 5, 3, 5, 6, 3};

void ag_draw_gilldoodleAfalleyesB(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleAfalleyesBvertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleAfalleyesBtexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleAfalleyesBtricount, vtxfmt,
		NULL, NULL, gilldoodleAfalleyesBvertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleAfalleyesBtexcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleAfalleyesB(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleAfalleyesB_config = LV_VPIDX16 | LV_TCIDX16;
