//Autogenerated triple quantized liym file with draw function
int gilldoodleBgetup8tricount = 11;
f32 gilldoodleBgetup8vertpos[] ATTRIBUTE_ALIGN(32) = {0.148022, -0.275349, 0.000000, 0.193128, -0.269193, 0.000000, 0.153226, -0.203032, 0.000000, -0.129107, -0.139691, 0.000000, 0.155398, 0.108341, 0.000000, -0.162854, 0.102827, 0.000000, -0.121741, -0.286554, 0.000000, -0.088777, -0.277298, 0.000000, -0.024431, -0.298886, 0.000000, 0.074653, 0.246889, 0.000000, -0.140571, 0.259186, 0.000000, -0.170879, 0.240534, 0.000000, -0.208464, -0.079651, 0.000000};
uint16_t gilldoodleBgetup8vertposidx[] = {0, 1, 2, 3, 4, 5, 3, 6, 7, 7, 8, 3, 8, 0, 2, 3, 8, 2, 2, 4, 3, 4, 9, 5, 9, 10, 5, 10, 11, 5, 5, 12, 3};
f32 gilldoodleBgetup8texcord[] ATTRIBUTE_ALIGN(32) = {0.973375, 0.369965, 0.995928, 0.366887, 0.975977, 0.333807, 0.837236, 0.301007, 0.987532, 0.173247, 0.829414, 0.175535, 0.838494, 0.375568, 0.854976, 0.370940, 0.887149, 0.381734, 0.953301, 0.101115, 0.845689, 0.094966, 0.830535, 0.104292, 0.799432, 0.270114};
uint16_t gilldoodleBgetup8texcordidx[] = {0, 1, 2, 3, 4, 5, 3, 6, 7, 7, 8, 3, 8, 0, 2, 3, 8, 2, 2, 4, 3, 4, 9, 5, 9, 10, 5, 10, 11, 5, 5, 12, 3};

void ag_draw_gilldoodleBgetup8(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleBgetup8vertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleBgetup8texcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleBgetup8tricount, vtxfmt,
		NULL, NULL, gilldoodleBgetup8vertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleBgetup8texcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleBgetup8(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleBgetup8_config = LV_VPIDX16 | LV_TCIDX16;
