//Autogenerated triple quantized liym file with draw function
int gilldoodleBgetup11tricount = 11;
f32 gilldoodleBgetup11vertpos[] ATTRIBUTE_ALIGN(32) = {0.147140, 0.163615, 0.000000, 0.063608, 0.199203, 0.000000, -0.135606, 0.007581, 0.000000, -0.138799, -0.152319, 0.000000, -0.128154, -0.212864, 0.000000, 0.183862, -0.324713, 0.000000, -0.060166, -0.353457, 0.000000, 0.012104, -0.369882, 0.000000, 0.148196, -0.361670, 0.000000, 0.195015, 0.149314, 0.000000, 0.126492, 0.206047, 0.000000, -0.027433, 0.245742, 0.000000, -0.144585, 0.154246, 0.000000};
uint16_t gilldoodleBgetup11vertposidx[] = {0, 1, 2, 3, 4, 5, 4, 6, 7, 7, 8, 5, 7, 5, 4, 5, 9, 3, 3, 9, 0, 0, 10, 1, 11, 12, 1, 12, 2, 1, 2, 3, 0};
f32 gilldoodleBgetup11texcord[] ATTRIBUTE_ALIGN(32) = {0.323358, 0.721297, 0.281592, 0.703503, 0.181985, 0.799314, 0.180388, 0.879264, 0.185711, 0.909536, 0.341719, 0.965460, 0.219705, 0.979832, 0.255840, 0.988045, 0.323886, 0.983939, 0.347295, 0.728447, 0.313034, 0.700081, 0.236071, 0.680233, 0.177495, 0.725981};
uint16_t gilldoodleBgetup11texcordidx[] = {0, 1, 2, 3, 4, 5, 4, 6, 7, 7, 8, 5, 7, 5, 4, 5, 9, 3, 3, 9, 0, 0, 10, 1, 11, 12, 1, 12, 2, 1, 2, 3, 0};

void ag_draw_gilldoodleBgetup11(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleBgetup11vertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleBgetup11texcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleBgetup11tricount, vtxfmt,
		NULL, NULL, gilldoodleBgetup11vertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleBgetup11texcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleBgetup11(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleBgetup11_config = LV_VPIDX16 | LV_TCIDX16;
