//Autogenerated triple quantized liym file with draw function
int gilldoodleBscramblearmAtricount = 10;
f32 gilldoodleBscramblearmAvertpos[] ATTRIBUTE_ALIGN(32) = {-0.015971, 0.010837, 0.000000, -0.012423, -0.001584, 0.000000, 0.010051, 0.001130, 0.000000, 0.034027, -0.164200, 0.000000, 0.016586, -0.020052, 0.000000, 0.046104, 0.018947, 0.000000, 0.054786, 0.063979, 0.000000, 0.016376, 0.113231, 0.000000, -0.083702, 0.069886, 0.000000, -0.039346, 0.015557, 0.000000, -0.083617, 0.043743, 0.000000, 0.057127, -0.151472, 0.000000};
uint16_t gilldoodleBscramblearmAvertposidx[] = {0, 1, 2, 3, 4, 1, 1, 4, 2, 2, 5, 0, 5, 6, 0, 6, 7, 0, 7, 8, 9, 0, 7, 9, 8, 10, 9, 3, 11, 4};
f32 gilldoodleBscramblearmAtexcord[] ATTRIBUTE_ALIGN(32) = {0.244326, 0.135943, 0.242234, 0.130250, 0.234901, 0.133960, 0.214846, 0.055717, 0.231172, 0.124302, 0.224117, 0.146488, 0.224483, 0.169413, 0.240933, 0.189406, 0.271312, 0.157614, 0.252501, 0.135771, 0.269383, 0.144849, 0.208032, 0.064386};
uint16_t gilldoodleBscramblearmAtexcordidx[] = {0, 1, 2, 3, 4, 1, 1, 4, 2, 2, 5, 0, 5, 6, 0, 6, 7, 0, 7, 8, 9, 0, 7, 9, 8, 10, 9, 3, 11, 4};

void ag_draw_gilldoodleBscramblearmA(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleBscramblearmAvertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleBscramblearmAtexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleBscramblearmAtricount, vtxfmt,
		NULL, NULL, gilldoodleBscramblearmAvertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleBscramblearmAtexcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleBscramblearmA(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleBscramblearmA_config = LV_VPIDX16 | LV_TCIDX16;
