//Autogenerated triple quantized liym file with draw function
int gilldoodleBswooshtricount = 3;
f32 gilldoodleBswooshvertpos[] ATTRIBUTE_ALIGN(32) = {0.048137, -0.108994, 0.000000, 0.085245, -0.074447, 0.000000, 0.004074, 0.042871, 0.000000, -0.053201, 0.171988, 0.000000, -0.115385, 0.090611, 0.000000};
uint16_t gilldoodleBswooshvertposidx[] = {0, 1, 2, 2, 3, 4, 4, 0, 2};
f32 gilldoodleBswooshtexcord[] ATTRIBUTE_ALIGN(32) = {0.296492, 0.145699, 0.309215, 0.128426, 0.281385, 0.069767, 0.261749, 0.005208, 0.240429, 0.045897};
uint16_t gilldoodleBswooshtexcordidx[] = {0, 1, 2, 2, 3, 4, 4, 0, 2};

void ag_draw_gilldoodleBswoosh(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleBswooshvertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleBswooshtexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleBswooshtricount, vtxfmt,
		NULL, NULL, gilldoodleBswooshvertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleBswooshtexcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleBswoosh(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleBswoosh_config = LV_VPIDX16 | LV_TCIDX16;
