//Autogenerated triple quantized liym file with draw function
int gilldoodleAsaddertricount = 15;
f32 gilldoodleAsaddervertpos[] ATTRIBUTE_ALIGN(32) = {-0.024250, 0.102187, 0.000000, -0.066967, 0.054691, 0.000000, 0.023763, 0.092244, 0.000000, -0.088070, -0.041862, 0.000000, -0.101632, -0.054500, 0.000000, -0.082577, -0.101213, 0.000000, -0.026298, -0.137777, 0.000000, 0.040735, -0.080781, 0.000000, 0.010982, -0.148889, 0.000000, 0.044678, -0.136343, 0.000000, 0.076582, -0.039557, 0.000000, 0.090008, 0.009224, 0.000000, 0.083125, 0.042346, 0.000000, 0.094310, 0.090954, 0.000000, -0.067432, 0.096218, 0.000000, 0.016316, 0.135785, 0.000000, -0.023273, 0.117272, 0.000000};
uint16_t gilldoodleAsaddervertposidx[] = {0, 1, 2, 3, 4, 5, 5, 6, 7, 6, 8, 7, 8, 9, 7, 7, 10, 1, 10, 11, 1, 12, 13, 2, 11, 12, 1, 1, 3, 7, 3, 5, 7, 0, 14, 1, 15, 16, 2, 16, 0, 2, 12, 2, 1};
f32 gilldoodleAsaddertexcord[] ATTRIBUTE_ALIGN(32) = {0.604170, 0.345917, 0.547248, 0.428152, 0.668151, 0.363132, 0.519127, 0.595324, 0.501055, 0.617205, 0.526446, 0.698085, 0.601441, 0.761391, 0.690766, 0.662708, 0.651119, 0.780631, 0.696021, 0.758908, 0.738534, 0.591333, 0.756425, 0.506874, 0.747254, 0.449526, 0.762157, 0.365366, 0.546628, 0.356252, 0.658226, 0.287746, 0.605472, 0.319800};
uint16_t gilldoodleAsaddertexcordidx[] = {0, 1, 2, 3, 4, 5, 5, 6, 7, 6, 8, 7, 8, 9, 7, 7, 10, 1, 10, 11, 1, 12, 13, 2, 11, 12, 1, 1, 3, 7, 3, 5, 7, 0, 14, 1, 15, 16, 2, 16, 0, 2, 12, 2, 1};

void ag_draw_gilldoodleAsadder(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleAsaddervertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleAsaddertexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleAsaddertricount, vtxfmt,
		NULL, NULL, gilldoodleAsaddervertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleAsaddertexcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleAsadder(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleAsadder_config = LV_VPIDX16 | LV_TCIDX16;
