//Autogenerated triple quantized liym file with draw function
int gilldoodleBdripAtricount = 4;
f32 gilldoodleBdripAvertpos[] ATTRIBUTE_ALIGN(32) = {0.026645, 0.020860, 0.000000, 0.034980, 0.073745, 0.000000, -0.016223, 0.036665, 0.000000, -0.044989, -0.027976, 0.000000, 0.016427, -0.043970, 0.000000, -0.016840, -0.059324, 0.000000};
uint16_t gilldoodleBdripAvertposidx[] = {0, 1, 2, 3, 4, 0, 0, 2, 3, 3, 5, 4};
f32 gilldoodleBdripAtexcord[] ATTRIBUTE_ALIGN(32) = {0.058060, 0.031219, 0.060918, 0.004776, 0.043363, 0.023317, 0.033500, 0.055637, 0.054557, 0.063634, 0.043151, 0.071311};
uint16_t gilldoodleBdripAtexcordidx[] = {0, 1, 2, 3, 4, 0, 0, 2, 3, 3, 5, 4};

void ag_draw_gilldoodleBdripA(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleBdripAvertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleBdripAtexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleBdripAtricount, vtxfmt,
		NULL, NULL, gilldoodleBdripAvertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleBdripAtexcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleBdripA(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleBdripA_config = LV_VPIDX16 | LV_TCIDX16;
