//Autogenerated triple quantized liym file with draw function
int gilldoodleBstartricount = 4;
f32 gilldoodleBstarvertpos[] ATTRIBUTE_ALIGN(32) = {-0.014899, -0.078341, 0.000000, 0.002592, -0.098842, 0.000000, 0.009125, -0.087198, 0.000000, 0.067901, 0.017559, 0.000000, 0.006146, 0.101596, 0.000000, -0.067029, -0.017240, 0.000000};
uint16_t gilldoodleBstarvertposidx[] = {0, 1, 2, 0, 2, 3, 3, 4, 5, 5, 0, 3};
f32 gilldoodleBstartexcord[] ATTRIBUTE_ALIGN(32) = {0.167319, 0.089969, 0.173316, 0.100219, 0.175556, 0.094397, 0.195707, 0.042019, 0.174535, 0.000000, 0.149447, 0.059418};
uint16_t gilldoodleBstartexcordidx[] = {0, 1, 2, 0, 2, 3, 3, 4, 5, 5, 0, 3};

void ag_draw_gilldoodleBstar(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleBstarvertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleBstartexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleBstartricount, vtxfmt,
		NULL, NULL, gilldoodleBstarvertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleBstartexcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleBstar(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleBstar_config = LV_VPIDX16 | LV_TCIDX16;
