//Autogenerated triple quantized liym file with draw function
int gilldoodleBgetup13tricount = 7;
f32 gilldoodleBgetup13vertpos[] ATTRIBUTE_ALIGN(32) = {-0.117810, 0.173186, 0.000000, -0.256858, -0.043063, 0.000000, 0.008744, -0.184852, 0.000000, 0.121177, 0.076548, 0.000000, -0.244365, 0.142293, 0.000000, -0.245452, -0.202279, 0.000000, -0.071099, -0.203071, 0.000000, 0.262397, -0.136533, 0.000000, 0.271631, 0.077340, 0.000000};
uint16_t gilldoodleBgetup13vertposidx[] = {0, 1, 2, 3, 0, 2, 0, 4, 1, 1, 5, 6, 6, 2, 1, 2, 7, 3, 7, 8, 3};
f32 gilldoodleBgetup13texcord[] ATTRIBUTE_ALIGN(32) = {0.705002, 0.645013, 0.635478, 0.753137, 0.768279, 0.824032, 0.824496, 0.693332, 0.641725, 0.660459, 0.641181, 0.832745, 0.728358, 0.833141, 0.895106, 0.799872, 0.899722, 0.692936};
uint16_t gilldoodleBgetup13texcordidx[] = {0, 1, 2, 3, 0, 2, 0, 4, 1, 1, 5, 6, 6, 2, 1, 2, 7, 3, 7, 8, 3};

void ag_draw_gilldoodleBgetup13(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleBgetup13vertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleBgetup13texcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleBgetup13tricount, vtxfmt,
		NULL, NULL, gilldoodleBgetup13vertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleBgetup13texcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleBgetup13(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleBgetup13_config = LV_VPIDX16 | LV_TCIDX16;
