//Autogenerated triple quantized liym file with draw function
int gilldoodleBtripBtricount = 11;
f32 gilldoodleBtripBvertpos[] ATTRIBUTE_ALIGN(32) = {0.101786, 0.155290, 0.000000, 0.059611, 0.224522, 0.000000, -0.025668, 0.144373, 0.000000, 0.197626, 0.129465, 0.000000, 0.189023, -0.123760, 0.000000, -0.198753, 0.171089, 0.000000, -0.242719, 0.116918, 0.000000, -0.249263, -0.060753, 0.000000, 0.093320, 0.242381, 0.000000, -0.187969, -0.090681, 0.000000, 0.161648, -0.157980, 0.000000, 0.260980, -0.135166, 0.000000, 0.307126, -0.069009, 0.000000};
uint16_t gilldoodleBtripBvertposidx[] = {0, 1, 2, 3, 0, 4, 2, 5, 6, 6, 7, 2, 7, 0, 2, 0, 8, 1, 0, 7, 9, 9, 10, 0, 10, 4, 0, 4, 11, 12, 12, 3, 4};
f32 gilldoodleBtripBtexcord[] ATTRIBUTE_ALIGN(32) = {0.465135, 0.329168, 0.444047, 0.294552, 0.401408, 0.334626, 0.513055, 0.342080, 0.508753, 0.468693, 0.314865, 0.321268, 0.292882, 0.348354, 0.289611, 0.437189, 0.460902, 0.285622, 0.320257, 0.452153, 0.495066, 0.485802, 0.544732, 0.474396, 0.567805, 0.441317};
uint16_t gilldoodleBtripBtexcordidx[] = {0, 1, 2, 3, 0, 4, 2, 5, 6, 6, 7, 2, 7, 0, 2, 0, 8, 1, 0, 7, 9, 9, 10, 0, 10, 4, 0, 4, 11, 12, 12, 3, 4};

void ag_draw_gilldoodleBtripB(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleBtripBvertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleBtripBtexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleBtripBtricount, vtxfmt,
		NULL, NULL, gilldoodleBtripBvertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleBtripBtexcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleBtripB(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleBtripB_config = LV_VPIDX16 | LV_TCIDX16;
