//Autogenerated triple quantized liym file with draw function
int gilldoodleBscramblelegsBtricount = 5;
f32 gilldoodleBscramblelegsBvertpos[] ATTRIBUTE_ALIGN(32) = {0.019667, 0.101946, 0.000000, -0.115331, -0.002687, 0.000000, 0.001188, -0.102198, 0.000000, 0.138708, -0.140970, 0.000000, 0.118340, 0.039236, 0.000000, -0.079703, 0.096808, 0.000000, -0.218424, -0.052435, 0.000000};
uint16_t gilldoodleBscramblelegsBvertposidx[] = {0, 1, 2, 2, 3, 4, 4, 0, 2, 0, 5, 1, 1, 6, 2};
f32 gilldoodleBscramblelegsBtexcord[] ATTRIBUTE_ALIGN(32) = {0.198049, 0.294055, 0.130551, 0.346372, 0.188810, 0.396127, 0.257570, 0.415514, 0.247386, 0.325410, 0.148364, 0.296624, 0.079004, 0.371246};
uint16_t gilldoodleBscramblelegsBtexcordidx[] = {0, 1, 2, 2, 3, 4, 4, 0, 2, 0, 5, 1, 1, 6, 2};

void ag_draw_gilldoodleBscramblelegsB(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleBscramblelegsBvertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleBscramblelegsBtexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleBscramblelegsBtricount, vtxfmt,
		NULL, NULL, gilldoodleBscramblelegsBvertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleBscramblelegsBtexcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleBscramblelegsB(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleBscramblelegsB_config = LV_VPIDX16 | LV_TCIDX16;
