//Autogenerated triple quantized liym file with draw function
int gilldoodleAfalleyesAtricount = 11;
f32 gilldoodleAfalleyesAvertpos[] ATTRIBUTE_ALIGN(32) = {-0.004570, -0.036193, 0.000000, -0.023728, 0.014705, 0.000000, -0.043564, 0.018495, 0.000000, -0.045137, -0.037572, 0.000000, -0.068786, -0.030353, 0.000000, 0.048463, 0.029682, 0.000000, 0.017761, -0.004754, 0.000000, 0.053234, -0.028818, 0.000000, -0.002569, -0.024129, 0.000000, -0.084468, -0.003717, 0.000000, 0.017138, -0.021350, 0.000000, 0.034771, -0.030685, 0.000000, 0.076883, -0.015334, 0.000000, 0.082276, 0.005619, 0.000000, 0.076468, 0.026570, 0.000000};
uint16_t gilldoodleAfalleyesAvertposidx[] = {0, 1, 2, 3, 2, 4, 5, 6, 7, 0, 8, 1, 0, 2, 3, 2, 9, 4, 10, 11, 6, 11, 7, 6, 7, 12, 5, 12, 13, 5, 13, 14, 5};
f32 gilldoodleAfalleyesAtexcord[] ATTRIBUTE_ALIGN(32) = {0.165506, 0.301599, 0.139976, 0.213474, 0.113544, 0.206910, 0.111448, 0.303985, 0.079935, 0.291486, 0.236174, 0.187542, 0.195262, 0.247164, 0.242532, 0.288828, 0.168172, 0.280711, 0.059037, 0.245369, 0.194433, 0.275898, 0.217930, 0.292061, 0.274046, 0.265482, 0.281233, 0.229205, 0.273493, 0.192929};
uint16_t gilldoodleAfalleyesAtexcordidx[] = {0, 1, 2, 3, 2, 4, 5, 6, 7, 0, 8, 1, 0, 2, 3, 2, 9, 4, 10, 11, 6, 11, 7, 6, 7, 12, 5, 12, 13, 5, 13, 14, 5};

void ag_draw_gilldoodleAfalleyesA(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleAfalleyesAvertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleAfalleyesAtexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleAfalleyesAtricount, vtxfmt,
		NULL, NULL, gilldoodleAfalleyesAvertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleAfalleyesAtexcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleAfalleyesA(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleAfalleyesA_config = LV_VPIDX16 | LV_TCIDX16;
