//Autogenerated triple quantized liym file with draw function
int gilldoodleBgetup7tricount = 15;
f32 gilldoodleBgetup7vertpos[] ATTRIBUTE_ALIGN(32) = {-0.019259, 0.330632, 0.000000, -0.143098, 0.210544, 0.000000, 0.156071, 0.186780, 0.000000, 0.155053, 0.122047, 0.000000, -0.140478, -0.005515, 0.000000, -0.121078, -0.047890, 0.000000, -0.067140, -0.215464, 0.000000, -0.001661, -0.273283, 0.000000, 0.092848, -0.209596, 0.000000, 0.111098, 0.289439, 0.000000, -0.110509, 0.320807, 0.000000, 0.155513, 0.151306, 0.000000, -0.138959, -0.036334, 0.000000, -0.074917, -0.252329, 0.000000, 0.168455, -0.271382, 0.000000, 0.152812, -0.020438, 0.000000, -0.092950, -0.046647, 0.000000};
uint16_t gilldoodleBgetup7vertposidx[] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 2, 0, 10, 1, 1, 4, 11, 2, 1, 11, 11, 4, 3, 4, 12, 5, 6, 13, 7, 7, 14, 8, 8, 15, 16, 15, 3, 16, 3, 5, 16, 16, 6, 8};
f32 gilldoodleBgetup7texcord[] ATTRIBUTE_ALIGN(32) = {0.743379, 0.000000, 0.681459, 0.060044, 0.831044, 0.071926, 0.830535, 0.104292, 0.682769, 0.168074, 0.692469, 0.189261, 0.719439, 0.273048, 0.752178, 0.301958, 0.799432, 0.270114, 0.808557, 0.020597, 0.697754, 0.004913, 0.830765, 0.089663, 0.683529, 0.183483, 0.715550, 0.291480, 0.837236, 0.301007, 0.829414, 0.175535, 0.706533, 0.188640};
uint16_t gilldoodleBgetup7texcordidx[] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 2, 0, 10, 1, 1, 4, 11, 2, 1, 11, 11, 4, 3, 4, 12, 5, 6, 13, 7, 7, 14, 8, 8, 15, 16, 15, 3, 16, 3, 5, 16, 16, 6, 8};

void ag_draw_gilldoodleBgetup7(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleBgetup7vertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleBgetup7texcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleBgetup7tricount, vtxfmt,
		NULL, NULL, gilldoodleBgetup7vertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleBgetup7texcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleBgetup7(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleBgetup7_config = LV_VPIDX16 | LV_TCIDX16;
