//Autogenerated triple quantized liym file with draw function
int gilldoodleAwaveArmBtricount = 7;
f32 gilldoodleAwaveArmBvertpos[] ATTRIBUTE_ALIGN(32) = {-0.025895, 0.024451, 0.000000, 0.005413, 0.014558, 0.000000, 0.017908, 0.027601, 0.000000, -0.007543, -0.065959, 0.000000, 0.012173, -0.066318, 0.000000, 0.019497, 0.010108, 0.000000, 0.010022, 0.072767, 0.000000, -0.029768, 0.059504, 0.000000, -0.001807, -0.076713, 0.000000};
uint16_t gilldoodleAwaveArmBvertposidx[] = {0, 1, 2, 3, 4, 5, 1, 5, 2, 2, 6, 7, 7, 0, 2, 5, 1, 3, 3, 8, 4};
f32 gilldoodleAwaveArmBtexcord[] ATTRIBUTE_ALIGN(32) = {0.424808, 0.763850, 0.466528, 0.780978, 0.483178, 0.758397, 0.449263, 0.920387, 0.475535, 0.921007, 0.485295, 0.788683, 0.472669, 0.680196, 0.419647, 0.703160, 0.456906, 0.939006};
uint16_t gilldoodleAwaveArmBtexcordidx[] = {0, 1, 2, 3, 4, 5, 1, 5, 2, 2, 6, 7, 7, 0, 2, 5, 1, 3, 3, 8, 4};

void ag_draw_gilldoodleAwaveArmB(int vtxfmt) {
	GX_SetArray(GX_VA_POS, &gilldoodleAwaveArmBvertpos[0], 12);
	GX_SetArray(GX_VA_TEX0, &gilldoodleAwaveArmBtexcord[0], 8);
	drawArrConfig(LV_VPIDX16 | LV_TCIDX16, gilldoodleAwaveArmBtricount, vtxfmt,
		NULL, NULL, gilldoodleAwaveArmBvertposidx,
		NULL, NULL, NULL,
		NULL, NULL, gilldoodleAwaveArmBtexcordidx,
		NULL,
		NULL);
}

void ag_config_gilldoodleAwaveArmB(int vtxfmt) {
	liy_VtxDescConfig(LV_VPIDX16 | LV_TCIDX16, vtxfmt);
}

int gilldoodleAwaveArmB_config = LV_VPIDX16 | LV_TCIDX16;
