//Autogenerated triple quantized liym file
int hallwaycorkboardtricount = 4;
f32 hallwaycorkboardvertpos[] ATTRIBUTE_ALIGN(32) = {29.686298, 7.267302, 5.489722, 25.640308, 7.267302, 11.498768, 25.640308, 7.267302, 5.489722, 21.594318, 7.267302, 11.498768, 21.594318, 7.267302, 5.489722, 29.686298, 7.267302, 11.498768};
uint16_t hallwaycorkboardvertposidx[] = {0, 1, 2, 2, 3, 4, 0, 5, 1, 2, 1, 3};
f32 hallwaycorkboardtexcord[] ATTRIBUTE_ALIGN(32) = {-0.361788, 0.500000, 1.359473, 1.000000, -0.361788, 1.000000, 1.359473, 0.500000};
uint16_t hallwaycorkboardtexcordidx[] = {0, 1, 2, 0, 1, 2, 0, 3, 1, 0, 3, 1};
uint8_t hallwaycorkboardvertcol[] = {133, 99, 61, 151, 113, 69, 145, 108, 67, 145, 108, 67, 163, 121, 75, 156, 116, 72, 133, 99, 61, 139, 104, 64, 151, 113, 69, 145, 108, 67, 151, 113, 69, 163, 121, 75};
