void drawDoodle(float * atf) {
	GX_SetCullMode(GX_CULL_NONE);
	uint b = 260;
	GX_SetTevColorIn(GX_TEVSTAGE0, GX_CC_ZERO, GX_CC_ZERO, GX_CC_ZERO, GX_CC_RASC);
	GX_SetTevColorOp(GX_TEVSTAGE0, GX_TEV_ADD, GX_TB_ZERO, GX_CS_SCALE_1, GX_TRUE, GX_TEVPREV);
	GX_SetTevOrder(GX_TEVSTAGE0, GX_TEXCOORDNULL, GX_TEXMAP_NULL, GX_COLOR0A0);
	GX_SetBlendMode(GX_BM_NONE, GX_BL_ONE, GX_BL_ZERO, GX_LO_NOOP);
	GX_SetChanCtrl(GX_COLOR0A0, GX_DISABLE, GX_SRC_VTX, GX_SRC_VTX, GX_LIGHTNULL, GX_DF_NONE, GX_AF_NONE);
	liyt_genMtxPosRotZyxScale(model, atf[b++] - 0.5, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], -atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_config_pagebackdrop(0);
	ag_draw_pagebackdrop(0);
	b = 0;
	GX_SetNumTevStages(1);
	GX_SetTevColorIn(GX_TEVSTAGE0, GX_CC_ZERO, GX_CC_ONE, GX_CC_TEXC, GX_CC_ZERO);
	GX_SetTevColorOp(GX_TEVSTAGE0, GX_TEV_ADD, GX_TB_ZERO, GX_CS_SCALE_1, GX_TRUE, GX_TEVPREV);
	GX_SetTevOrder(GX_TEVSTAGE0, GX_TEXCOORD0, GX_TEXMAP0, GX_COLORNULL);
	GX_SetBlendMode(GX_BM_SUBTRACT, GX_BL_ONE, GX_BL_ZERO, GX_LO_NOOP);
	GX_SetCurrentMtx(GX_PNMTX0);
	GX_LoadTexObj(&gillDoodleTexATexObj, GX_TEXMAP0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_config_gilldoodleAsurprise(0); ag_draw_gilldoodleAsurprise(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleAwave(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleAwaveArmA(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleAwaveArmB(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleAblowerA(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleAblowerB(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleAfallhead(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleAfalleyesA(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleAfalleyesB(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleAfalltorsoA(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleAfalltorsoB(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleAheart(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleAsadder(0);
	GX_LoadTexObj(&gilldoodlescrambleTexObj, GX_TEXMAP0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleBdripA(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleBdripB(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleBgetup1(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleBgetup2(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleBgetup3(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleBgetup4(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleBgetup5(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleBgetup6(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleBgetup7(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleBgetup8(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleBgetup9(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleBgetup10(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleBgetup11(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleBgetup12(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleBgetup13(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleBswoosh(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleBtripA(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleBtripB(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleBscrambletorso(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleBscramblearmA(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleBscramblearmB(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleBscramblelegsA(0);
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_gilldoodleBscramblelegsB(0);
	
	//heres where the massive switch statement goes to decide what texture to load
	u8 gay = 1;
	switch((int)atf[259]) {
		case 0:  GX_LoadTexObj(&laketiltdown1TexObj, GX_TEXMAP0); break;
		case 1:  GX_LoadTexObj(&laketiltdown2TexObj, GX_TEXMAP0); break;
		case 2:  GX_LoadTexObj(&laketiltdown3TexObj, GX_TEXMAP0); break;
		case 3:  GX_LoadTexObj(&laketiltdown4TexObj, GX_TEXMAP0); break;
		case 4:  GX_LoadTexObj(&laketiltdown5TexObj, GX_TEXMAP0); break;

		case 5:  GX_LoadTexObj(&lakeusquat2TexObj, GX_TEXMAP0); break;
		case 6:  GX_LoadTexObj(&lakeusquat3TexObj, GX_TEXMAP0); break;
		case 7:  GX_LoadTexObj(&lakeusquat4TexObj, GX_TEXMAP0); break;
		case 8:  GX_LoadTexObj(&lakeusquat5TexObj, GX_TEXMAP0); break;
		
		case 9:  GX_LoadTexObj(&lakevstand2TexObj, GX_TEXMAP0); break;
		case 10: GX_LoadTexObj(&lakevstand3TexObj, GX_TEXMAP0); break;
		case 11: GX_LoadTexObj(&lakevstand4TexObj, GX_TEXMAP0); break;
		case 12: GX_LoadTexObj(&lakevstand45TexObj, GX_TEXMAP0); break;
		case 13: GX_LoadTexObj(&lakevstand5TexObj, GX_TEXMAP0); break;

		case 14: GX_LoadTexObj(&lakewalk1TexObj, GX_TEXMAP0); break;
		case 15: GX_LoadTexObj(&lakewalk2TexObj, GX_TEXMAP0); break;
		case 16: GX_LoadTexObj(&lakewalk3TexObj, GX_TEXMAP0); break;
		case 17: GX_LoadTexObj(&lakewalk4TexObj, GX_TEXMAP0); break;

		case 18: GX_LoadTexObj(&riverturn7TexObj, GX_TEXMAP0); gay--; break;
		case 19: GX_LoadTexObj(&riverturn6TexObj, GX_TEXMAP0); gay--; break;
		case 20: GX_LoadTexObj(&riverturn5TexObj, GX_TEXMAP0); gay--; break;
		case 21: GX_LoadTexObj(&riverturn4TexObj, GX_TEXMAP0); gay--; break;
		case 22: GX_LoadTexObj(&riverturn3TexObj, GX_TEXMAP0); gay--; break;
		case 23: GX_LoadTexObj(&riverturn2TexObj, GX_TEXMAP0); gay--; break;
		case 24: GX_LoadTexObj(&riverturn1TexObj, GX_TEXMAP0); gay--; break;

		case 25: GX_LoadTexObj(&lakeoutstretch1TexObj, GX_TEXMAP0); break;
		case 26: GX_LoadTexObj(&lakeoutstretch2TexObj, GX_TEXMAP0); break;
		case 27: GX_LoadTexObj(&lakeoutstretch3TexObj, GX_TEXMAP0); break;
		case 28: GX_LoadTexObj(&lakeoutstretch4TexObj, GX_TEXMAP0); break;
		case 29: GX_LoadTexObj(&lakeoutstretch5TexObj, GX_TEXMAP0); break;
		case 30: GX_LoadTexObj(&lakeoutstretch6TexObj, GX_TEXMAP0); break;
		case 31: GX_LoadTexObj(&lakeoutstretch7TexObj, GX_TEXMAP0); break;
		case 32: GX_LoadTexObj(&lakeoutstretch8TexObj, GX_TEXMAP0); break;
		case 33: GX_LoadTexObj(&lakeoutstretch9TexObj, GX_TEXMAP0); break;
		case 34: GX_LoadTexObj(&lakeoutstretch10TexObj, GX_TEXMAP0); break;
		case 35: GX_LoadTexObj(&lakeoutstretch11TexObj, GX_TEXMAP0); break;

		case 36: GX_LoadTexObj(&hand1TexObj, GX_TEXMAP0); break;
		case 37: GX_LoadTexObj(&hand2TexObj, GX_TEXMAP0); break;
		case 38: GX_LoadTexObj(&hand3TexObj, GX_TEXMAP0); break;
		case 39: GX_LoadTexObj(&hand4TexObj, GX_TEXMAP0); break;
		case 40: GX_LoadTexObj(&hand5TexObj, GX_TEXMAP0); break;
		case 41: GX_LoadTexObj(&hand6TexObj, GX_TEXMAP0); break;
		case 42: GX_LoadTexObj(&hand7TexObj, GX_TEXMAP0); break;
		case 43: GX_LoadTexObj(&hand8TexObj, GX_TEXMAP0); break;
		case 44: GX_LoadTexObj(&hand9TexObj, GX_TEXMAP0); break;
		case 45: GX_LoadTexObj(&hand10TexObj, GX_TEXMAP0); break;
		case 46: GX_LoadTexObj(&hand11TexObj, GX_TEXMAP0); break;
		case 47: GX_LoadTexObj(&hand12TexObj, GX_TEXMAP0); break;
		case 48: GX_LoadTexObj(&hand13TexObj, GX_TEXMAP0); break;
		case 49: GX_LoadTexObj(&hand14TexObj, GX_TEXMAP0); break;
		case 50: GX_LoadTexObj(&hand15TexObj, GX_TEXMAP0); break;
		case 51: GX_LoadTexObj(&hand16TexObj, GX_TEXMAP0); break;
		case 52: GX_LoadTexObj(&hand17TexObj, GX_TEXMAP0); break;
		
		case 53: GX_LoadTexObj(&guycarry1TexObj, GX_TEXMAP0); break;
		case 54: GX_LoadTexObj(&guycarry2TexObj, GX_TEXMAP0); break;
		case 55: GX_LoadTexObj(&guycarry3TexObj, GX_TEXMAP0); break;
		case 56: GX_LoadTexObj(&guycarry4TexObj, GX_TEXMAP0); break;
		case 57: GX_LoadTexObj(&guycarry5TexObj, GX_TEXMAP0); break;
		case 58: GX_LoadTexObj(&guycarry6TexObj, GX_TEXMAP0); break;
		case 59: GX_LoadTexObj(&guycarry7TexObj, GX_TEXMAP0); break;
		case 60: GX_LoadTexObj(&guycarry8TexObj, GX_TEXMAP0); break;
		case 61: GX_LoadTexObj(&guycarry9TexObj, GX_TEXMAP0); break;
		case 62: GX_LoadTexObj(&guycarry10TexObj, GX_TEXMAP0); break;
		case 63: GX_LoadTexObj(&guycarry11TexObj, GX_TEXMAP0); break;
		case 64: GX_LoadTexObj(&guycarry12TexObj, GX_TEXMAP0); break;
		case 65: GX_LoadTexObj(&guycarry13TexObj, GX_TEXMAP0); break;
		case 66: GX_LoadTexObj(&guycarry14TexObj, GX_TEXMAP0); break;
		case 67: GX_LoadTexObj(&guycarry15TexObj, GX_TEXMAP0); break;
		case 68: GX_LoadTexObj(&guycarry16TexObj, GX_TEXMAP0); break;
		case 69: GX_LoadTexObj(&guycarry17TexObj, GX_TEXMAP0); break;
		case 70: GX_LoadTexObj(&guycarry18TexObj, GX_TEXMAP0); break;
		case 71: GX_LoadTexObj(&guycarry19TexObj, GX_TEXMAP0); break;
		case 72: GX_LoadTexObj(&guycarry20TexObj, GX_TEXMAP0); break;
		case 73: GX_LoadTexObj(&guycarry21TexObj, GX_TEXMAP0); break;
		

		default:
			break;
	}
	liyt_genMtxDoodle(model, atf[b++], atf[b++], atf[b++], atf[b++], gay? -atf[b++] : atf[b++], atf[b++], atf[b++]);
	guMtxConcat(view, model, model); GX_LoadPosMtxImm(model, GX_PNMTX0);
	ag_draw_doodle1(0);
	b++;
	GX_SetBlendMode(GX_BM_NONE, GX_BL_ONE, GX_BL_ZERO, GX_LO_NOOP);
}